#ifndef _GLELP_WGLEXT_H_
#define _GLELP_WGLEXT_H_

#include "glcorearb.h"
#include "wglext.h"

namespace glelp
{
	bool initWindowsExtensions();

}


//init_WGL_ARB_buffer_region
#ifdef define_WGL_ARB_buffer_region
extern PFNWGLCREATEBUFFERREGIONARBPROC wglCreateBufferRegionARB;
extern PFNWGLDELETEBUFFERREGIONARBPROC wglDeleteBufferRegionARB;
extern PFNWGLSAVEBUFFERREGIONARBPROC wglSaveBufferRegionARB;
extern PFNWGLRESTOREBUFFERREGIONARBPROC wglRestoreBufferRegionARB;

#endif


//init_WGL_ARB_create_context
#ifdef define_WGL_ARB_create_context
extern PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB;

#endif


//init_WGL_ARB_create_context_profile
#ifdef define_WGL_ARB_create_context_profile

#endif


//init_WGL_ARB_create_context_robustness
#ifdef define_WGL_ARB_create_context_robustness

#endif


//init_WGL_ARB_extensions_string
#ifdef define_WGL_ARB_extensions_string
extern PFNWGLGETEXTENSIONSSTRINGARBPROC wglGetExtensionsStringARB;

#endif


//init_WGL_ARB_framebuffer_sRGB
#ifdef define_WGL_ARB_framebuffer_sRGB

#endif


//init_WGL_ARB_make_current_read
#ifdef define_WGL_ARB_make_current_read
extern PFNWGLMAKECONTEXTCURRENTARBPROC wglMakeContextCurrentARB;
extern PFNWGLGETCURRENTREADDCARBPROC wglGetCurrentReadDCARB;

#endif


//init_WGL_ARB_multisample
#ifdef define_WGL_ARB_multisample

#endif


//init_WGL_ARB_pbuffer
#ifdef define_WGL_ARB_pbuffer
extern PFNWGLCREATEPBUFFERARBPROC wglCreatePbufferARB;
extern PFNWGLGETPBUFFERDCARBPROC wglGetPbufferDCARB;
extern PFNWGLRELEASEPBUFFERDCARBPROC wglReleasePbufferDCARB;
extern PFNWGLDESTROYPBUFFERARBPROC wglDestroyPbufferARB;
extern PFNWGLQUERYPBUFFERARBPROC wglQueryPbufferARB;

#endif


//init_WGL_ARB_pixel_format
#ifdef define_WGL_ARB_pixel_format
extern PFNWGLGETPIXELFORMATATTRIBIVARBPROC wglGetPixelFormatAttribivARB;
extern PFNWGLGETPIXELFORMATATTRIBFVARBPROC wglGetPixelFormatAttribfvARB;
extern PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB;

#endif


//init_WGL_ARB_pixel_format_float
#ifdef define_WGL_ARB_pixel_format_float

#endif


//init_WGL_ARB_render_texture
#ifdef define_WGL_ARB_render_texture
extern PFNWGLBINDTEXIMAGEARBPROC wglBindTexImageARB;
extern PFNWGLRELEASETEXIMAGEARBPROC wglReleaseTexImageARB;
extern PFNWGLSETPBUFFERATTRIBARBPROC wglSetPbufferAttribARB;

#endif


//init_WGL_ARB_robustness_application_isolation
#ifdef define_WGL_ARB_robustness_application_isolation

#endif


//init_WGL_ARB_robustness_share_group_isolation
#ifdef define_WGL_ARB_robustness_share_group_isolation

#endif


//init_WGL_3DFX_multisample
#ifdef define_WGL_3DFX_multisample

#endif


//init_WGL_3DL_stereo_control
#ifdef define_WGL_3DL_stereo_control
extern PFNWGLSETSTEREOEMITTERSTATE3DLPROC wglSetStereoEmitterState3DL;

#endif


//init_WGL_AMD_gpu_association
#ifdef define_WGL_AMD_gpu_association
extern PFNWGLGETGPUIDSAMDPROC wglGetGPUIDsAMD;
extern PFNWGLGETGPUINFOAMDPROC wglGetGPUInfoAMD;
extern PFNWGLGETCONTEXTGPUIDAMDPROC wglGetContextGPUIDAMD;
extern PFNWGLCREATEASSOCIATEDCONTEXTAMDPROC wglCreateAssociatedContextAMD;
extern PFNWGLCREATEASSOCIATEDCONTEXTATTRIBSAMDPROC wglCreateAssociatedContextAttribsAMD;
extern PFNWGLDELETEASSOCIATEDCONTEXTAMDPROC wglDeleteAssociatedContextAMD;
extern PFNWGLMAKEASSOCIATEDCONTEXTCURRENTAMDPROC wglMakeAssociatedContextCurrentAMD;
extern PFNWGLGETCURRENTASSOCIATEDCONTEXTAMDPROC wglGetCurrentAssociatedContextAMD;
extern PFNWGLBLITCONTEXTFRAMEBUFFERAMDPROC wglBlitContextFramebufferAMD;

#endif


//init_WGL_ATI_pixel_format_float
#ifdef define_WGL_ATI_pixel_format_float

#endif


//init_WGL_EXT_create_context_es2_profile
#ifdef define_WGL_EXT_create_context_es2_profile

#endif


//init_WGL_EXT_create_context_es_profile
#ifdef define_WGL_EXT_create_context_es_profile

#endif


//init_WGL_EXT_depth_float
#ifdef define_WGL_EXT_depth_float

#endif


//init_WGL_EXT_display_color_table
#ifdef define_WGL_EXT_display_color_table
extern PFNWGLCREATEDISPLAYCOLORTABLEEXTPROC wglCreateDisplayColorTableEXT;
extern PFNWGLLOADDISPLAYCOLORTABLEEXTPROC wglLoadDisplayColorTableEXT;
extern PFNWGLBINDDISPLAYCOLORTABLEEXTPROC wglBindDisplayColorTableEXT;
extern PFNWGLDESTROYDISPLAYCOLORTABLEEXTPROC wglDestroyDisplayColorTableEXT;

#endif


//init_WGL_EXT_extensions_string
#ifdef define_WGL_EXT_extensions_string
extern PFNWGLGETEXTENSIONSSTRINGEXTPROC wglGetExtensionsStringEXT;

#endif


//init_WGL_EXT_framebuffer_sRGB
#ifdef define_WGL_EXT_framebuffer_sRGB

#endif


//init_WGL_EXT_make_current_read
#ifdef define_WGL_EXT_make_current_read
extern PFNWGLMAKECONTEXTCURRENTEXTPROC wglMakeContextCurrentEXT;
extern PFNWGLGETCURRENTREADDCEXTPROC wglGetCurrentReadDCEXT;

#endif


//init_WGL_EXT_multisample
#ifdef define_WGL_EXT_multisample

#endif


//init_WGL_EXT_pbuffer
#ifdef define_WGL_EXT_pbuffer
extern PFNWGLCREATEPBUFFEREXTPROC wglCreatePbufferEXT;
extern PFNWGLGETPBUFFERDCEXTPROC wglGetPbufferDCEXT;
extern PFNWGLRELEASEPBUFFERDCEXTPROC wglReleasePbufferDCEXT;
extern PFNWGLDESTROYPBUFFEREXTPROC wglDestroyPbufferEXT;
extern PFNWGLQUERYPBUFFEREXTPROC wglQueryPbufferEXT;

#endif


//init_WGL_EXT_pixel_format
#ifdef define_WGL_EXT_pixel_format
extern PFNWGLGETPIXELFORMATATTRIBIVEXTPROC wglGetPixelFormatAttribivEXT;
extern PFNWGLGETPIXELFORMATATTRIBFVEXTPROC wglGetPixelFormatAttribfvEXT;
extern PFNWGLCHOOSEPIXELFORMATEXTPROC wglChoosePixelFormatEXT;

#endif


//init_WGL_EXT_pixel_format_packed_float
#ifdef define_WGL_EXT_pixel_format_packed_float

#endif


//init_WGL_EXT_swap_control
#ifdef define_WGL_EXT_swap_control
extern PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT;
extern PFNWGLGETSWAPINTERVALEXTPROC wglGetSwapIntervalEXT;

#endif


//init_WGL_EXT_swap_control_tear
#ifdef define_WGL_EXT_swap_control_tear

#endif


//init_WGL_I3D_digital_video_control
#ifdef define_WGL_I3D_digital_video_control
extern PFNWGLGETDIGITALVIDEOPARAMETERSI3DPROC wglGetDigitalVideoParametersI3D;
extern PFNWGLSETDIGITALVIDEOPARAMETERSI3DPROC wglSetDigitalVideoParametersI3D;

#endif


//init_WGL_I3D_gamma
#ifdef define_WGL_I3D_gamma
extern PFNWGLGETGAMMATABLEPARAMETERSI3DPROC wglGetGammaTableParametersI3D;
extern PFNWGLSETGAMMATABLEPARAMETERSI3DPROC wglSetGammaTableParametersI3D;
extern PFNWGLGETGAMMATABLEI3DPROC wglGetGammaTableI3D;
extern PFNWGLSETGAMMATABLEI3DPROC wglSetGammaTableI3D;

#endif


//init_WGL_I3D_genlock
#ifdef define_WGL_I3D_genlock
extern PFNWGLENABLEGENLOCKI3DPROC wglEnableGenlockI3D;
extern PFNWGLDISABLEGENLOCKI3DPROC wglDisableGenlockI3D;
extern PFNWGLISENABLEDGENLOCKI3DPROC wglIsEnabledGenlockI3D;
extern PFNWGLGENLOCKSOURCEI3DPROC wglGenlockSourceI3D;
extern PFNWGLGETGENLOCKSOURCEI3DPROC wglGetGenlockSourceI3D;
extern PFNWGLGENLOCKSOURCEEDGEI3DPROC wglGenlockSourceEdgeI3D;
extern PFNWGLGETGENLOCKSOURCEEDGEI3DPROC wglGetGenlockSourceEdgeI3D;
extern PFNWGLGENLOCKSAMPLERATEI3DPROC wglGenlockSampleRateI3D;
extern PFNWGLGETGENLOCKSAMPLERATEI3DPROC wglGetGenlockSampleRateI3D;
extern PFNWGLGENLOCKSOURCEDELAYI3DPROC wglGenlockSourceDelayI3D;
extern PFNWGLGETGENLOCKSOURCEDELAYI3DPROC wglGetGenlockSourceDelayI3D;
extern PFNWGLQUERYGENLOCKMAXSOURCEDELAYI3DPROC wglQueryGenlockMaxSourceDelayI3D;

#endif


//init_WGL_I3D_image_buffer
#ifdef define_WGL_I3D_image_buffer
extern PFNWGLCREATEIMAGEBUFFERI3DPROC wglCreateImageBufferI3D;
extern PFNWGLDESTROYIMAGEBUFFERI3DPROC wglDestroyImageBufferI3D;
extern PFNWGLASSOCIATEIMAGEBUFFEREVENTSI3DPROC wglAssociateImageBufferEventsI3D;
extern PFNWGLRELEASEIMAGEBUFFEREVENTSI3DPROC wglReleaseImageBufferEventsI3D;

#endif


//init_WGL_I3D_swap_frame_lock
#ifdef define_WGL_I3D_swap_frame_lock
extern PFNWGLENABLEFRAMELOCKI3DPROC wglEnableFrameLockI3D;
extern PFNWGLDISABLEFRAMELOCKI3DPROC wglDisableFrameLockI3D;
extern PFNWGLISENABLEDFRAMELOCKI3DPROC wglIsEnabledFrameLockI3D;
extern PFNWGLQUERYFRAMELOCKMASTERI3DPROC wglQueryFrameLockMasterI3D;

#endif


//init_WGL_I3D_swap_frame_usage
#ifdef define_WGL_I3D_swap_frame_usage
extern PFNWGLGETFRAMEUSAGEI3DPROC wglGetFrameUsageI3D;
extern PFNWGLBEGINFRAMETRACKINGI3DPROC wglBeginFrameTrackingI3D;
extern PFNWGLENDFRAMETRACKINGI3DPROC wglEndFrameTrackingI3D;
extern PFNWGLQUERYFRAMETRACKINGI3DPROC wglQueryFrameTrackingI3D;

#endif


//init_WGL_NV_DX_interop
#ifdef define_WGL_NV_DX_interop
extern PFNWGLDXSETRESOURCESHAREHANDLENVPROC wglDXSetResourceShareHandleNV;
extern PFNWGLDXOPENDEVICENVPROC wglDXOpenDeviceNV;
extern PFNWGLDXCLOSEDEVICENVPROC wglDXCloseDeviceNV;
extern PFNWGLDXREGISTEROBJECTNVPROC wglDXRegisterObjectNV;
extern PFNWGLDXUNREGISTEROBJECTNVPROC wglDXUnregisterObjectNV;
extern PFNWGLDXOBJECTACCESSNVPROC wglDXObjectAccessNV;
extern PFNWGLDXLOCKOBJECTSNVPROC wglDXLockObjectsNV;
extern PFNWGLDXUNLOCKOBJECTSNVPROC wglDXUnlockObjectsNV;

#endif


//init_WGL_NV_DX_interop2
#ifdef define_WGL_NV_DX_interop2

#endif


//init_WGL_NV_copy_image
#ifdef define_WGL_NV_copy_image
extern PFNWGLCOPYIMAGESUBDATANVPROC wglCopyImageSubDataNV;

#endif


//init_WGL_NV_delay_before_swap
#ifdef define_WGL_NV_delay_before_swap
extern PFNWGLDELAYBEFORESWAPNVPROC wglDelayBeforeSwapNV;

#endif


//init_WGL_NV_float_buffer
#ifdef define_WGL_NV_float_buffer

#endif


//init_WGL_NV_gpu_affinity
#ifdef define_WGL_NV_gpu_affinity
extern PFNWGLENUMGPUSNVPROC wglEnumGpusNV;
extern PFNWGLENUMGPUDEVICESNVPROC wglEnumGpuDevicesNV;
extern PFNWGLCREATEAFFINITYDCNVPROC wglCreateAffinityDCNV;
extern PFNWGLENUMGPUSFROMAFFINITYDCNVPROC wglEnumGpusFromAffinityDCNV;
extern PFNWGLDELETEDCNVPROC wglDeleteDCNV;

#endif


//init_WGL_NV_multisample_coverage
#ifdef define_WGL_NV_multisample_coverage

#endif


//init_WGL_NV_present_video
#ifdef define_WGL_NV_present_video
extern PFNWGLENUMERATEVIDEODEVICESNVPROC wglEnumerateVideoDevicesNV;
extern PFNWGLBINDVIDEODEVICENVPROC wglBindVideoDeviceNV;
extern PFNWGLQUERYCURRENTCONTEXTNVPROC wglQueryCurrentContextNV;

#endif


//init_WGL_NV_render_depth_texture
#ifdef define_WGL_NV_render_depth_texture

#endif


//init_WGL_NV_render_texture_rectangle
#ifdef define_WGL_NV_render_texture_rectangle

#endif


//init_WGL_NV_swap_group
#ifdef define_WGL_NV_swap_group
extern PFNWGLJOINSWAPGROUPNVPROC wglJoinSwapGroupNV;
extern PFNWGLBINDSWAPBARRIERNVPROC wglBindSwapBarrierNV;
extern PFNWGLQUERYSWAPGROUPNVPROC wglQuerySwapGroupNV;
extern PFNWGLQUERYMAXSWAPGROUPSNVPROC wglQueryMaxSwapGroupsNV;
extern PFNWGLQUERYFRAMECOUNTNVPROC wglQueryFrameCountNV;
extern PFNWGLRESETFRAMECOUNTNVPROC wglResetFrameCountNV;

#endif


//init_WGL_NV_vertex_array_range
#ifdef define_WGL_NV_vertex_array_range
extern PFNWGLALLOCATEMEMORYNVPROC wglAllocateMemoryNV;
extern PFNWGLFREEMEMORYNVPROC wglFreeMemoryNV;

#endif


//init_WGL_NV_video_capture
#ifdef define_WGL_NV_video_capture
extern PFNWGLBINDVIDEOCAPTUREDEVICENVPROC wglBindVideoCaptureDeviceNV;
extern PFNWGLENUMERATEVIDEOCAPTUREDEVICESNVPROC wglEnumerateVideoCaptureDevicesNV;
extern PFNWGLLOCKVIDEOCAPTUREDEVICENVPROC wglLockVideoCaptureDeviceNV;
extern PFNWGLQUERYVIDEOCAPTUREDEVICENVPROC wglQueryVideoCaptureDeviceNV;
extern PFNWGLRELEASEVIDEOCAPTUREDEVICENVPROC wglReleaseVideoCaptureDeviceNV;

#endif


//init_WGL_NV_video_output
#ifdef define_WGL_NV_video_output
extern PFNWGLGETVIDEODEVICENVPROC wglGetVideoDeviceNV;
extern PFNWGLRELEASEVIDEODEVICENVPROC wglReleaseVideoDeviceNV;
extern PFNWGLBINDVIDEOIMAGENVPROC wglBindVideoImageNV;
extern PFNWGLRELEASEVIDEOIMAGENVPROC wglReleaseVideoImageNV;
extern PFNWGLSENDPBUFFERTOVIDEONVPROC wglSendPbufferToVideoNV;
extern PFNWGLGETVIDEOINFONVPROC wglGetVideoInfoNV;

#endif


//init_WGL_OML_sync_control
#ifdef define_WGL_OML_sync_control
extern PFNWGLGETSYNCVALUESOMLPROC wglGetSyncValuesOML;
extern PFNWGLGETMSCRATEOMLPROC wglGetMscRateOML;
extern PFNWGLSWAPBUFFERSMSCOMLPROC wglSwapBuffersMscOML;
extern PFNWGLSWAPLAYERBUFFERSMSCOMLPROC wglSwapLayerBuffersMscOML;
extern PFNWGLWAITFORMSCOMLPROC wglWaitForMscOML;
extern PFNWGLWAITFORSBCOMLPROC wglWaitForSbcOML;

#endif


#endif // _GLELP_WGLEXT_H_
